# Managed by Ansible! October 2023
#
# List more
alias lls="ls -lAh"
# Kill DNS
alias dns="sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache"
# Kill zombie VMs
alias nobrains='sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart'
# update homebrew
alias bu="brew update && brew outdated && brew upgrade && brew cleanup -s"
# make host work more sensibly
alias h4="host -t A"
alias h6="host -t AAAA"
