# Managed by Ansible!
#
# List more
alias lls="ls -lAh"
# Kill DNS
alias dns="sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache"
# Kill zombie VMs
alias nobrains='sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart'
# update homebrew
alias bu="brew update && brew upgrade && brew cleanup -s"
